spring.application.name=demo

spring.datasource.url=jdbc:mysql://autorack.proxy.rlwy.net:26878/railway?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=eHKvxLqLWoAQgxQdifIWvuaFxcMwXuHk
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080